export const FETCH_USER_INFORMATION_REQUEST = 'FETCH_USER_INFORMATION_REQUEST';
export const FETCH_USER_INFORMATION_SUCCESS = 'FETCH_USER_INFORMATION_SUCCESS';
export const FETCH_USER_INFORMATION_FAILURE = 'FETCH_USER_INFORMATION_FAILURE';
export const DELETE_USER_INFORMATION_REQUEST = 'DELETE_USER_INFORMATION_REQUEST';
export const DELETE_USER_INFORMATION_FAILURE = 'DELETE_USER_INFORMATION_FAILURE';
export const DELETE_USER_INFORMATION_SUCCESS = 'DELETE_USER_INFORMATION_SUCCESS';

export const FETCH_STORE_INFORMATION_REQUEST = 'FETCH_STORE_INFORMATION_REQUEST';
export const FETCH_STORE_INFORMATION_SUCCESS = 'FETCH_STORE_INFORMATION_SUCCESS';
export const FETCH_STORE_INFORMATION_FAILURE = 'FETCH_STORE_INFORMATION_FAILURE';
